version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
    - bodyclose

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  exclude-rules:
    # Test files may use simpler patterns
    - path: "_test\\.go"
      linters:
        - errcheck
        - gosec
